
const VectorTransformVerifier = artifacts.require("VectorTransformVerifier");

module.exports = function(deployer) {
  // Replace this with the actual verification key generated by EZKL
  const verificationKey = "0x1234567890123456789012345678901234567890123456789012345678901234";
  
  deployer.deploy(VectorTransformVerifier, verificationKey);
};
